export const images={campus:'/images/campus.webp',concert:'/images/concert.webp',team:'/images/team.webp',portrait:'/images/portrait.webp'};
export const students=[
{id:'aarav',name:'Aarav Singh',initials:'AS',course:'CSE · 3rd Year',college:'Gyan Ganga Institute of Technology & Science',bio:'Building useful things with curious people. Looking for a hackathon team and a really good coffee.',skills:['Web Dev','AI/ML','Startups'],match:95,color:'#8868cf',photo:images.portrait},
{id:'riya',name:'Riya Sharma',initials:'RS',course:'CSE · 2nd Year',college:'GGITS, Jabalpur',bio:'Turning ideas into interfaces. Let’s build something that makes campus life better.',skills:['UI/UX','React','Photography'],match:92,color:'#bc6991'},
{id:'arjun',name:'Arjun Mehta',initials:'AM',course:'ECE · 3rd Year',college:'GGITS, Jabalpur',bio:'Robotics, late-night debugging and big ideas. Searching for my next project crew.',skills:['Robotics','Python','IoT'],match:89,color:'#557b9c'},
{id:'sneha',name:'Sneha Verma',initials:'SV',course:'CSE · 3rd Year',college:'GGITS, Jabalpur',bio:'Exploring machine learning, books and everything in between.',skills:['AI/ML','Python','Reading'],match:94,color:'#b88059'},
{id:'tanvi',name:'Tanvi Singh',initials:'TS',course:'BBA · 1st Year',college:'GGITS, Jabalpur',bio:'Music, stories and bringing people together.',skills:['Music','Marketing','Design'],match:86,color:'#779b8f'}];
export const events=[
{id:'techfest',title:'TechFest 2026',type:'Hackathons',date:'Sep 28, 2026',venue:'Main Campus Auditorium',count:'1.2K',image:images.concert,description:'Build, collaborate and celebrate. Join a day of creative challenges, project demos and conversations with your campus community.',time:'9:00 AM – 6:00 PM'},
{id:'ai-workshop',title:'AI for Good Workshop',type:'Workshops',date:'Oct 12, 2026',venue:'Innovation Lab',count:'320',image:images.team,description:'A hands-on introduction to building responsible AI projects. Bring your laptop and an idea you want to explore.',time:'11:00 AM – 2:00 PM'},
{id:'cultural',title:'Under the Stars',type:'Cultural',date:'Nov 5, 2026',venue:'Open-air Theatre',count:'980',image:images.concert,description:'An evening of live music, student performances and campus memories.',time:'6:00 PM – 9:00 PM'},
{id:'startup',title:'Startup Weekend',type:'Technical',date:'Nov 18, 2026',venue:'Seminar Hall',count:'450',image:images.team,description:'Find a team, shape an idea and pitch your first prototype.',time:'10:00 AM – 5:00 PM'}];
export const clubs=[
{id:'coding',name:'Coding Club',category:'Coding',tagline:'Build. Learn. Innovate.',members:'1.2K',image:images.team,description:'A space for curious builders. Weekly coding sessions, project nights and teammates for your next hackathon.'},
{id:'photography',name:'Photography Club',category:'Photography',tagline:'Capture. Create. Share.',members:'860',image:images.campus,description:'See campus from a new angle. Photo walks, editing sessions and a community of visual storytellers.'},
{id:'robotics',name:'Robotics Club',category:'Robotics',tagline:'Think. Build. Automate.',members:'780',image:images.team,description:'From your first circuit to a working robot, build and learn together in the lab.'},
{id:'music',name:'Music Club',category:'Music',tagline:'Feel the beat. Together.',members:'770',image:images.concert,description:'Bring your instrument or just your love of music. Join open mics, jam sessions and campus performances.'},
{id:'sports',name:'Campus Athletics',category:'Sports',tagline:'Play for the team.',members:'540',image:images.campus,description:'Friendly games, volleyball practice and a team that always has room for one more.'}];
export const announcements=[
{id:1,category:'Important',title:'Mid-Semester Exam Schedule Released',summary:'Check your branch-wise schedule now.',detail:'Check your branch-wise timetable with your department coordinator. Confirm your subjects and examination room with your faculty.',time:'2 hours ago'},
{id:2,category:'Placement',title:'Placement Registration Open',summary:'Complete your student profile before September 30.',detail:'Prepare an updated resume and contact the training and placement cell for eligibility and official registration instructions.',time:'5 hours ago'},
{id:3,category:'Events',title:'TechFest 2026 — Call for Volunteers',summary:'Be a part of something big!',detail:'Help with event coordination, design, hospitality or technical support. Visit the TechFest event page to register your interest.',time:'1 day ago'},
{id:4,category:'Academic',title:'Library Timings Updated',summary:'More time for your next big idea.',detail:'Check the library desk for the current opening hours.',time:'2 days ago'},
{id:5,category:'General',title:'New Clubs Open for Registration',summary:'Explore and join your interest-based clubs.',detail:'Find your people in Coding, Photography, Robotics, Music and Sports. Explore Clubs to join a community.',time:'2 days ago'}];
export const initialPosts=[{id:'p1',author:'aarav',caption:'Late nights. Big ideas. Great people. 🚀 Our next hackathon project starts right here. Who’s building with us?',image:images.team,likes:128,time:'2 hours ago',type:'Posts'}, {id:'p2',author:'riya',caption:'A little campus magic after the last lecture. 💜',image:images.campus,likes:92,time:'4 hours ago',type:'Posts'}, {id:'p3',author:'sneha',caption:'Still thinking about this night. See you at TechFest! ✨',image:images.concert,likes:236,time:'Yesterday',type:'Reels'}];
export const initialConversations=[{id:'aarav',name:'Aarav Singh',last:'Bro, are you coming to the hackathon?',time:'10:24 AM',unread:2},{id:'sneha',name:'Sneha Verma',last:'Let’s meet at the library!',time:'9:41 AM',unread:0},{id:'project',name:'Project Squad',last:'Rohan: Sharing the deck here…',time:'Yesterday',group:true,unread:0},{id:'design',name:'Design Club',last:'Tanya: Poster looks amazing! ✨',time:'Yesterday',group:true,unread:0},{id:'arjun',name:'Arjun Mehta',last:'Sure, see you!',time:'Mon',unread:0}];
