import React, { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { Bookmark, Film, Image as ImageIcon, Loader2, LogOut, Pencil, Shield, X } from "lucide-react";
import { disconnectChatSocket } from "./api/chatSocket";
import { fetchMe, fetchSavedContent, fetchUserPosts, fetchUserReels, updateUserProfile } from "./api/client";

function isProfileActive(){return Array.from(document.querySelectorAll("button")).some(b=>b.textContent?.trim()==="Profile"&&(b.getAttribute("style")||"").includes("109, 93, 246"));}
function findProfileContentTarget(){const tabs=Array.from(document.querySelectorAll("button")).filter(b=>["Posts","Reels","Tagged","About"].includes(b.textContent?.trim()));if(tabs.length<4)return null;return tabs[0].parentElement?.nextElementSibling||null;}
function CardGrid({items,kind}){if(!items.length)return <div style={{padding:34,textAlign:"center",color:"rgba(242,241,251,.58)"}}>{kind==="reels"?"No reels yet.":"No posts yet."}</div>;return <div className="cm-profile-grid" style={{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:6}}>{items.map(item=>{const media=kind==="reels"?item.thumbnailUrl||item.videoUrl:item.media?.[0]?.url;return <div key={item._id} style={{aspectRatio:kind==="reels"?"9/16":"1/1",borderRadius:10,overflow:"hidden",background:"rgba(255,255,255,.06)",position:"relative",display:"grid",placeItems:"center"}}>{media?<img src={media} alt="" loading="lazy" style={{width:"100%",height:"100%",objectFit:"cover"}}/>:kind==="reels"?<Film size={20}/>:<ImageIcon size={20}/>}</div>})}</div>}
function Modal({title,onClose,children}){return <div style={{position:"fixed",inset:0,zIndex:15000,background:"rgba(0,0,0,.68)",display:"grid",placeItems:"center",padding:"max(16px,env(safe-area-inset-top)) max(16px,env(safe-area-inset-right)) max(16px,env(safe-area-inset-bottom)) max(16px,env(safe-area-inset-left))"}}><div style={{width:"min(100%,460px)",maxHeight:"88dvh",overflowY:"auto",borderRadius:20,background:"#111526",border:"1px solid rgba(255,255,255,.12)",color:"#f4f2ff",padding:18}}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:14}}><strong>{title}</strong><button onClick={onClose} style={iconBtn}><X size={17}/></button></div>{children}</div></div>}
const inputStyle={width:"100%",borderRadius:12,border:"1px solid rgba(255,255,255,.12)",background:"rgba(255,255,255,.04)",color:"#f4f2ff",padding:"10px 12px",fontSize:13};
const iconBtn={width:44,height:44,borderRadius:11,border:"1px solid rgba(255,255,255,.12)",background:"transparent",color:"#fff",display:"grid",placeItems:"center"};
const rowBtn={width:"100%",minHeight:50,borderRadius:14,border:"1px solid rgba(255,255,255,.1)",background:"rgba(255,255,255,.035)",color:"#f4f2ff",display:"flex",alignItems:"center",gap:10,padding:"0 14px",fontWeight:700,cursor:"pointer"};
const primaryBtn={minHeight:44,border:"none",borderRadius:12,background:"linear-gradient(135deg,#6D5DF6,#A855F7)",color:"white",fontWeight:800,padding:"0 16px",cursor:"pointer"};
export default function PhaseFProfileLayer(){const[active,setActive]=useState(false),[target,setTarget]=useState(null),[portalHost,setPortalHost]=useState(null),[tab,setTab]=useState("posts"),[me,setMe]=useState(null),[posts,setPosts]=useState([]),[reels,setReels]=useState([]),[saved,setSaved]=useState({posts:[],reels:[]}),[loading,setLoading]=useState(false),[modal,setModal]=useState(null),[error,setError]=useState(""),[form,setForm]=useState({name:"",bio:"",branch:"",year:"",lookingFor:"",interests:""}),[privacy,setPrivacy]=useState("campus");
const load=async()=>{if(!localStorage.getItem("cm_token"))return;setLoading(true);setError("");try{const user=await fetchMe();setMe(user);const[p,r,s]=await Promise.all([fetchUserPosts(user._id),fetchUserReels(user._id),fetchSavedContent(user._id)]);setPosts(p||[]);setReels(r||[]);setSaved(s||{posts:[],reels:[]});setPrivacy(user.privacy||"campus");setForm({name:user.name||"",bio:user.bio||"",branch:user.branch||"",year:user.year||"",lookingFor:user.lookingFor||"",interests:(user.interests||[]).join(", ")});}catch(e){setError(e?.response?.data?.message||"Could not load profile.");}finally{setLoading(false);}};
useEffect(()=>{const sync=()=>{setActive(isProfileActive());setTarget(findProfileContentTarget());};sync();const mo=new MutationObserver(sync);mo.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:["style"]});return()=>mo.disconnect();},[]);useEffect(()=>{if(active)load();},[active]);useEffect(()=>{if(!active)return;const refresh=()=>load();window.addEventListener("cm-media-uploaded",refresh);return()=>window.removeEventListener("cm-media-uploaded",refresh);},[active]);useEffect(()=>{if(!active)return;const handler=e=>{const b=e.target instanceof Element?e.target.closest("button"):null;if(!b)return;const label=b.textContent?.trim();if(["Posts","Reels","Tagged","About"].includes(label))setTab(label.toLowerCase());};document.addEventListener("click",handler,true);return()=>document.removeEventListener("click",handler,true);},[active]);
useEffect(()=>{if(!target)return;const old=target.style.display;target.style.display="none";let host=target.parentElement?.querySelector(":scope > [data-cm-profile-live]");if(!host){host=document.createElement("div");host.dataset.cmProfileLive="1";target.parentElement?.appendChild(host);}setPortalHost(host);return()=>{target.style.display=old;host?.remove();setPortalHost(null);};},[target]);
const saveProfile=async()=>{if(!me)return;setError("");try{const user=await updateUserProfile(me._id,{name:form.name,bio:form.bio,branch:form.branch,year:form.year,lookingFor:form.lookingFor,interests:form.interests.split(",").map(x=>x.trim()).filter(Boolean)});setMe(user);setModal(null);window.dispatchEvent(new CustomEvent("cm-profile-updated",{detail:{user}}));await load();}catch(e){setError(e?.response?.data?.message||"Could not save profile.");}};
const savePrivacy=async()=>{if(!me)return;setError("");try{const user=await updateUserProfile(me._id,{privacy});setMe(user);setModal(null);window.dispatchEvent(new CustomEvent("cm-profile-updated",{detail:{user}}));}catch(e){setError(e?.response?.data?.message||"Could not save privacy.");}};
const logout=()=>{disconnectChatSocket();localStorage.removeItem("cm_token");window.dispatchEvent(new Event("cm-auth-expired"));window.location.reload();};
const body=useMemo(()=>{if(loading)return <div style={{padding:36,display:"grid",placeItems:"center"}}><Loader2 size={22}/></div>;if(error)return <div style={{padding:28,textAlign:"center",color:"#fb7185"}}>{error}<div><button onClick={load} style={{...primaryBtn,marginTop:12}}>Retry</button></div></div>;if(tab==="posts")return <CardGrid items={posts} kind="posts"/>;if(tab==="reels")return <CardGrid items={reels} kind="reels"/>;if(tab==="tagged")return <div style={{padding:34,textAlign:"center",color:"rgba(242,241,251,.58)"}}>No tagged posts yet.</div>;return <div style={{display:"grid",gap:9}}><button onClick={()=>setModal("edit")} style={rowBtn}><Pencil size={16}/>Edit Profile</button><button onClick={()=>setModal("privacy")} style={rowBtn}><Shield size={16}/>Privacy Settings</button><button onClick={()=>setModal("saved")} style={rowBtn}><Bookmark size={16}/>Content You Saved <span style={{marginLeft:"auto",opacity:.6}}>{(saved.posts?.length||0)+(saved.reels?.length||0)}</span></button><button onClick={logout} style={{...rowBtn,color:"#fb7185"}}><LogOut size={16}/>Log Out</button></div>},[loading,error,tab,posts,reels,saved]);
if(!active||!portalHost)return null;return <>{createPortal(<div style={{marginTop:14}}>{body}</div>,portalHost)}{modal==="edit"&&<Modal title="Edit Profile" onClose={()=>setModal(null)}><div style={{display:"grid",gap:10}}><input style={inputStyle} value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value}))} placeholder="Name"/><textarea style={{...inputStyle,minHeight:90}} value={form.bio} onChange={e=>setForm(f=>({...f,bio:e.target.value}))} placeholder="Bio"/><input style={inputStyle} value={form.branch} onChange={e=>setForm(f=>({...f,branch:e.target.value}))} placeholder="Branch"/><input style={inputStyle} value={form.year} onChange={e=>setForm(f=>({...f,year:e.target.value}))} placeholder="Year"/><input style={inputStyle} value={form.lookingFor} onChange={e=>setForm(f=>({...f,lookingFor:e.target.value}))} placeholder="Looking for"/><input style={inputStyle} value={form.interests} onChange={e=>setForm(f=>({...f,interests:e.target.value}))} placeholder="Interests, comma separated"/>{error&&<div style={{color:"#fb7185",fontSize:12}}>{error}</div>}<button onClick={saveProfile} style={primaryBtn}>Save profile</button></div></Modal>}{modal==="privacy"&&<Modal title="Privacy Settings" onClose={()=>setModal(null)}><select style={inputStyle} value={privacy} onChange={e=>setPrivacy(e.target.value)}><option value="campus">Campus only</option><option value="public">Public</option><option value="private">Private</option></select>{error&&<div style={{color:"#fb7185",fontSize:12,marginTop:8}}>{error}</div>}<button onClick={savePrivacy} style={{...primaryBtn,marginTop:12}}>Save privacy</button></Modal>}{modal==="saved"&&<Modal title="Saved Content" onClose={()=>setModal(null)}><div style={{fontSize:12,opacity:.65,marginBottom:10}}>Saved posts</div><CardGrid items={saved.posts||[]} kind="posts"/><div style={{fontSize:12,opacity:.65,margin:"16px 0 10px"}}>Saved reels</div><CardGrid items={saved.reels||[]} kind="reels"/></Modal>}</>}
